export const DEBUG_SOURCE_MAPS_ENV = 'SHOCKPKG_CLI_DEBUG_SOURCE_MAPS';

export const DEBUG_STACK_TRACE_ENV = 'SHOCKPKG_CLI_DEBUG_STACK_TRACE';

export const DEBUG_ERROR_LOG = 'SHOCKPKG_CLI_DEBUG_ERROR_LOG';

export const UPDATE_INTERVAL_DEFAULT = 1000;

export const UPDATE_INTERVAL_ENV = 'SHOCKPKG_CLI_UPDATE_INTERVAL';
